#include "emlib/src/em_acmp.c"
#include "emlib/src/em_adc.c"
#include "emlib/src/em_aes.c"

/* void assertEFM(const char* file, int line) move to debug.c huaweiwx@sina.com */
//#include "emlib/src/em_assert.c" 

#include "emlib/src/em_burtc.c"
#include "emlib/src/em_cmu.c"
#include "emlib/src/em_core.c"
#include "emlib/src/em_cryotimer.c"
#include "emlib/src/em_crypto.c"
#include "emlib/src/em_csen.c"
#include "emlib/src/em_dac.c"
#include "emlib/src/em_dbg.c"
#include "emlib/src/em_dma.c"
#include "emlib/src/em_ebi.c"
#include "emlib/src/em_emu.c"
#include "emlib/src/em_gpcrc.c"
#include "emlib/src/em_gpio.c"
#include "emlib/src/em_i2c.c"
#include "emlib/src/em_idac.c"
//#include "emlib/src/em_int.c"   /*deprecated and marked for removal in a later release*/
#include "emlib/src/em_lcd.c"
#include "emlib/src/em_ldma.c"
#include "emlib/src/em_lesense.c"
#include "emlib/src/em_leuart.c"
#include "emlib/src/em_mpu.c"
#include "emlib/src/em_msc.c"
#include "emlib/src/em_opamp.c"
#include "emlib/src/em_pcnt.c"
#include "emlib/src/em_prs.c"
#include "emlib/src/em_rmu.c"
#include "emlib/src/em_rtc.c"
#include "emlib/src/em_rtcc.c"
#include "emlib/src/em_system.c"
#include "emlib/src/em_timer.c"
#include "emlib/src/em_usart.c"
#include "emlib/src/em_vcmp.c"
#include "emlib/src/em_vdac.c"
#include "emlib/src/em_wdog.c"